-- ProjNav VHDL simulation template: TBW_SUBB_LIT5.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
